### ISSUE TITLE
Cannot connect MG400

### ISSUE THREAD

**Issue by raspberry-pi-maker** [Dobot-Arm/TCP-IP-Python#1]
HI
I'm using MG400. And its IP is "192.168.1.6".
And the MG 400 works well with old python SDK.
When I test the demo.py, The error message shows like this.

Fail to setup socket connection ! <class 'OSError'>
Fail to connect feedback server ! <class 'OSError'>
ClearError()
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\spypiggy\.conda\envs\py_3_8_11\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\spypiggy\.conda\envs\py_3_8_11\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\LSH\dobot\DobotSDK1.4.1\PythonDemo_Windows\tcp_demo.py", line 8, in main
    client_dashboard.ClearError()
  File "D:\LSH\dobot\DobotSDK1.4.1\PythonDemo_Windows\dobot_api.py", line 218, in ClearError
    self.socket_dashboard.send(str.encode(string, "utf-8"))

This is my demo.py
```python
dobot_ip = "192.168.1.6"
if __name__ == "__main__":
    client_dashboard = dobot_api_dashboard(dobot_ip, 29999)
    client_feedback = dobot_api_feedback(dobot_ip, 30003)
    p1 = Process(target=main, args=(client_dashboard, client_feedback))
    p1.start()
    p2 = Process(target=data_feedback, args=(client_feedback,))
    p2.daemon = True
    p2.start()
    p1.join()
    client_dashboard.close()
    client_feedback.close()
```

**Comment by LSinterbotix** [comment]
I'm having the same issue with a CR3. When trying to connect to 192.168.1.6 port numbers 29999 and 30003, I'm seeing the error `ConnectionRefusedError: [Errno 111] Connection refused` .

The simple script below gives the same error:
```Python
import socket

if __name__ == "__main__":
    s = socket.socket()
    s.connect(("192.168.1.6", 29999)) # <---
    s.close()
```
```console
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    s.connect(("192.168.1.6", 29999))
ConnectionRefusedError: [Errno 111] Connection refused
```

I'm able to ping the CR3 so connection is not the issue:
```console
$ ping 192.168.1.6
PING 192.168.1.6 (192.168.1.6) 56(84) bytes of data.
64 bytes from 192.168.1.6: icmp_seq=1 ttl=64 time=5.04 ms
64 bytes from 192.168.1.6: icmp_seq=2 ttl=64 time=5.79 ms
64 bytes from 192.168.1.6: icmp_seq=3 ttl=64 time=6.69 ms
64 bytes from 192.168.1.6: icmp_seq=4 ttl=64 time=5.19 ms
```

As asked above, are we supposed to update the firmware on the robot itself? Any help would be appreciated.

**Comment by peach777enjoy** [comment]
MG400 :wireless connection: ip is 192.168.9.1 .
Sorry, I will add it to README.md.

**Comment by raspberry-pi-maker** [comment]
Hi @peach777enjoy

I can't understand "wireless connection"
I don't use wireless network. I'm using wire connection. And the IP "192.168.1.6" is correct.
Python SDK works well with IP "192.168.1.6".

**Comment by peach777enjoy** [comment]
MG400 firmware need to update to 1.5.4.0 version.

![image](https://user-images.githubusercontent.com/32080770/133751627-5365d41a-ad11-49f6-878c-d862f0d840ba.png)

**Comment by Locotar** [comment]
> MG400 firmware need to update to 1.5.4.0 version. CR firmware need to update to 3.5.1.9 version. @raspberry-pi-maker @LSinterbotix ![image](https://user-images.githubusercontent.com/32080770/133751627-5365d41a-ad11-49f6-878c-d862f0d840ba.png)

Hi @peach777enjoy
Got the same issue in MG400, where can i get the newest firmware version?

<img width="426" alt="version_info_20211108" src="https://user-images.githubusercontent.com/13034696/140696798-d9960c54-90db-45d3-9bee-fdc2e1882b03.png">

**Comment by MartinPedersenpp** [comment]
Did you ever find the new firmware? I am currently going through the same issues and cannot find the firmware.

**Comment by LSinterbotix** [comment]
@MartinPedersenpp Try contacting Dobot support.

**Comment by MartinPedersenpp** [comment]
I can confirm this issue occurs if you are using dobotstudio2020 v1.5 and the controller firmware 1.5.0 or 1.5.1.
Upgrading the firmware of the controller with dobot SC studio or dobotstudio2020 v1.3 and then converting to the new dobotstudio2020 has solved the issue.
I got the new firmware from my product vendor.
